meta_product_name: "Bouquin Voisin"
meta_title: "Bouquin Voisin - Les bouquins préférés de vos voisins !"
meta_description: "A la recherche de conseils lecture ? Decouvrez les livres préférés de vos voisins. 
Bouquin Voisin, vous permet de consulter les livres favoris recommandés par vos voisins passionnés. Echanger, discuter, partager, rencontrer 
des voisins passionnés de lecture"
meta_image: "meta_image.jpg"
twitter_account: ""