meta_product_name: "Bouquin Voisin"
meta_title: "Bouquin Voisin - Les bouquins préférés de tes voisins !"
meta_description: "A la recherche de conseils lecture ? Decouvrez les livres préférés de tes voisins. 
Bouquin Voisin, te permet de consulter les livres favoris recommandés par tes voisins passionnés. Echanger, discuter, partager, rencontrer 
des voisins passionnés de lecture"
meta_image: "meta_image.jpg"
twitter_account: ""