# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create(email:"michel@bv.com", password: "azertyui", name: "Michel", date_of_birth: 12/12/1980, address: "75018")
User.create(email:"john@bv.com", password: "azertyui", name: "John", date_of_birth: 12/12/1980, address: "78 rue Gay Lussac, 75005")
User.create(email:"Alice@bv.com", password: "azertyui", name: "Alice", date_of_birth: 12/12/1980, address: "75019")
User.create(email:"Charlotte@bv.com", password: "azertyui", name: "Charlotte", date_of_birth: 12/12/1980, address: "30 rue de Thionville, Paris 75019")
User.create(email:"Anne@bv.com", password: "azertyui", name: "Anne", date_of_birth: 12/12/1980, address: "6 rue de Castellane, 75009")
User.create(email:"Valentin@bv.com", password: "azertyui", name: "Valentin", date_of_birth: 12/12/1980, address: "34 rue des Martyrs, 75009")
User.create(email:"Seb@bv.com", password: "azertyui", name: "Seb", date_of_birth: 12/12/1980, address: "75009")
User.create(email:"Lei@bv.com", password: "azertyui", name: "Lei", date_of_birth: 12/12/1980, address: "75020")
User.create(email:"fab@bv.com", password: "azertyui", name: "Fab", date_of_birth: 12/12/1980, address: "impasse Poule, 75020")
User.create(email:"Fanny@bv.com", password: "azertyui", name: "Fanny", date_of_birth: 12/12/1980, address: "rue Gay Lussac, 75005")


Book.create(title:"L'étranger", author:"Albert Camus", category:"Classique")
Book.create(title:"Du côté de chez Swann ", author:"Marcel Proust", category:"Classique")
Book.create(title:"Le Procès", author:"Franz Kafka", category:"Classique")
Book.create(title:"Le Petit Prince", author:"Antoine de Saint-Exupéry", category:"Classique")
Book.create(title:"La Condition Humaine", author:"André Malraux", category:"Classique")
Book.create(title:"Voyage au bout de la nuit", author:"Céline", category:"Classique")
Book.create(title:"Les Raisins de la colère ", author:"John Steinbeck", category:"Classique")
Book.create(title:"Pour qui sonne le glas", author:"Ernest Hemingway", category:"Classique")
Book.create(title:"Le Grand Meaulnes ", author:"Alain-Fournier", category:"Classique")
Book.create(title:"L'Écume des jours ", author:"Boris Vian", category:"Classique")
Book.create(title:"Le Deuxième Sexe, partie 1 ", author:"Simone de Beauvoir", category:"Classique")
Book.create(title:"En attendant Godot", author:"Samuel Beckett", category:"Classique")


Review.create(book_title:"L'étranger", book_author:"Albert Camus", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 1)
Review.create(book_title:"Du côté de chez Swann ", book_author:"Marcel Proust", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 2)
Review.create(book_title:"Le Procès", book_author:"Franz Kafka", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 3)
Review.create(book_title:"Le Petit Prince", book_author:"Antoine de Saint-Exupéry", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 4)
Review.create(book_title:"La Condition Humaine", book_author:"André Malraux", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 5)
Review.create(book_title:"Voyage au bout de la nuit", book_author:"Céline", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 6)
Review.create(book_title:"Les Raisins de la colère ", book_author:"John Steinbeck", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 1)
Review.create(book_title:"Pour qui sonne le glas", book_author:"Ernest Hemingway", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 2)
Review.create(book_title:"Le Grand Meaulnes ", book_author:"Alain-Fournier", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 3)
Review.create(book_title:"L'Écume des jours ", book_author:"Boris Vian", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 4)
Review.create(book_title:"Le Deuxième Sexe, partie 1 ", book_author:"Simone de Beauvoir", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 5)
Review.create(book_title:"En attendant Godot", book_author:"Samuel Beckett", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 6)
Review.create(book_title:"L'étranger", book_author:"Albert Camus", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 7)
Review.create(book_title:"Du côté de chez Swann ", book_author:"Marcel Proust", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 8)
Review.create(book_title:"Le Procès", book_author:"Franz Kafka", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 9)
Review.create(book_title:"Le Petit Prince", book_author:"Antoine de Saint-Exupéry", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 10)
Review.create(book_title:"La Condition Humaine", book_author:"André Malraux", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 11)
Review.create(book_title:"Voyage au bout de la nuit", book_author:"Céline", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 12)
Review.create(book_title:"Les Raisins de la colère ", book_author:"John Steinbeck", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 7)
Review.create(book_title:"Pour qui sonne le glas", book_author:"Ernest Hemingway", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 8)
Review.create(book_title:"Le Grand Meaulnes ", book_author:"Alain-Fournier", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 9)
Review.create(book_title:"L'Écume des jours ", book_author:"Boris Vian", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 10)
Review.create(book_title:"Le Deuxième Sexe, partie 1 ", book_author:"Simone de Beauvoir", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 11)
Review.create(book_title:"En attendant Godot", book_author:"Samuel Beckett", book_category:"Classique", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget est id est facilisis eleifend. Vivamus ipsum augue, vulputate id molestie nec, egestas nec urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc elementum maximus tempor. Ut viverra, ligula vel eleifend efficitur, nisi tortor placerat urna, ac condimentum nunc nulla quis dui. Etiam massa sem, vehicula eu pulvinar vitae, blandit in sem. Vestibulum eget fringilla velit, sed congue nisi. Curabitur eget porttitor dui. Nulla rutrum erat nec feugiat gravida. Mauris semper consectetur nisi, et faucibus erat tristique eget. Morbi non hendrerit tortor, at tincidunt sem. Curabitur quis lacus nec purus pellentesque mollis. Integer ac ante massa. Etiam tincidunt nunc ac lectus luctus, vitae placerat arcu placerat. ", user_id: 12)